name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - uses: fwal/setup-swift@main
      with:
        swift-version: "5.5.1"
    - name: Build
      run: xcodebuild -scheme 'DCFrame' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13 Pro,OS=15.0' build
    - name: Run tests
      run: xcodebuild -scheme 'DCFrame' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13 Pro,OS=15.0' test
